ember-cli/ember-cli-blueprint-test-helpers

- blueprints/ember-cli-blueprint-test-helpers/index.js
- package.json
Adding mocha as a dev-dep as well as adding to the default blueprint.
> Added mocha as dev-dep and to default blueprint index

- blueprints/ember-cli-blueprint-test-helpers/files/node-tests/fixtures/addon/package/package.json
- blueprints/ember-cli-blueprint-test-helpers/files/node-tests/fixtures/app/package/package.json
- lib/helpers/blueprint-helper.js
- lib/helpers/project-init.js
- lib/helpers/project-setup.js
- lib/helpers/project-teardown.js
- lib/helpers/setup.js
- lib/helpers/tmp-env.js
Added some more inline documentation and cleaned up the fixture package.json files in the default blueprint.
> Added documentation and cleaned up fixture packages

- lib/helpers/blueprint-helper.js
Previously: `AssertionError: expected app/router.js not to exist: expected false to be truthy`
Now: `AssertionError: app/router.js exists: expected true to be false`
> Improve assertion message in assertFileNotExists()

- appveyor.yml
- tests/unit/blueprint-helper-nodetest.js
> Add AppVeyor manifest

- README.md
This list was assembled from a GitHub search of the project name
> README: Add list of library users

- .eslintrc.js
- tests/acceptance/helpers-test.js
@Turbo87 so there are some issues with the new syntax not clearing eslint. I was just adding some tests, but decided to push this up to see if I could get some help figuring out what we should do to fix it.
> Acceptance test for emberGenerateDestroy

- node-tests/blueprints/blueprint-test-test.js
- node-tests/blueprints/ember-cli-blueprint-test-helpers-test.js
- tests/lint-test.js
> Fix ESLint issues

- node-tests/blueprints/ember-cli-blueprint-test-helpers-test.js
- package.json
> Fix failing blueprint test

- lib/helpers/setup.js
- package.json
Resolves #72
/cc @trabus @stefanpenner
> Remove expensive debug output calls

- lib/helpers/setup.js
Related, blocking: https://github.com/ember-cli/ember-cli/pull/6450
> Remove outdated helper.

- node-tests/blueprints/ember-cli-blueprint-test-helpers-test.js
turns out the complicated resolving wasn't necessary.
> simplify package lookup

- lib/helpers/setup.js
> use the new MockBlueprintTaskFor api

- README.md
- lib/helpers/setup.js
- node-tests/blueprints/ember-cli-blueprint-test-helpers-test.js
to test packages added to package.json using the real npm.
> add disableMocking option

- README.md
- lib/helpers/setup.js
Should probably join bower and npm as default
> add 'addon-install' to disabled tasks

- .travis.yml
> CI: Install npm@3 if necessary

- package.json
since we use TravisCI for publishing now
> package.json: Remove obsolete pre/postversion scripts

- package.json
> fix(package): update chai to version 4.1.0

- package.json
> remove rimraf

- package.json
- yarn.lock
I couldn't find it being used.
> remove findup

- package.json
- yarn.lock
> update mocha to 4

- blueprints/ember-cli-blueprint-test-helpers/index.js
Reverts ember-cli/ember-cli-blueprint-test-helpers#145
> Revert "use require to read package.json"

- package.json
- yarn.lock
This PR aims at using a released version of ember-cli following https://github.com/ember-cli/ember-cli-blueprint-test-helpers/pull/153
May you provide a release once this PR is settled? 🙏
> Use ember-cli v3.5.0-beta.1

- .travis.yml
- appveyor.yml
> Improve CI configuration

- .github_changelog_generator
- package.json
- yarn.lock
use `yarn changelog` to generate the changelog for new releases
/cc @dcyriller
> Add `lerna-changelog` dev dependency

- appveyor.yml
maaaaybe that fixes our CI issues?
> AppVeyor: Use `yarn` instead of `npm`
