ember-cli/ember-cli-blueprint-test-helpers

- blueprints/ember-cli-blueprint-test-helpers/index.js
Running `ember install ember-cli-blueprint-test-helpers` already installs the test helpers, no need to do it again.
> Remove this library from its own blueprint.

- blueprints/ember-cli-blueprint-test-helpers/files/node-tests/nodetest-runner.js
The main references were moved to `node-tests/` folder with a file ending in `-test.js` (not `-nodetest.js`).  These look like left-overs.
@trabus - Can you confirm?
> Remove extra references to `nodetest.js`.

- blueprints/ember-cli-blueprint-test-helpers/files/node-tests/nodetest-runner.js
Since `root` already includes `node-tests`, this was actually looking for files in `node-tests/node-tests/**/*-test.js`.
> Remove double `node-tests` prefix.

- blueprints/ember-cli-blueprint-test-helpers/index.js
This updates the used version of `ember-cli-internal-test-helpers` to the recently released `0.6.0`. This is based on the work done in  1fefa40fa845871a2ad251b0940b89ab2b7a2b25.
> Bump version of dependency in blueprint

- blueprints/ember-cli-blueprint-test-helpers/files/.npmignore
- blueprints/ember-cli-blueprint-test-helpers/index.js
- lib/helpers/blueprint-helper.js
- lib/helpers/project-init.js
- package.json
Removed unnecessary installs for default blueprint, and updating `.npmignore` through `insertIntoFile` (fixing #3).
Also bumped ember-cli to 2.3.0-beta.2
> Blueprint fixes

- lib/helpers/blueprint-helper.js
- package.json
Fixes #19
Also bumped ember-cli to `2.3.0` and ember-cli-internal-test-helpers to `0.8.1`
> Fixes #19 use expect().to.be.true in assertions

- package.json
seems to be no longer needed with extraction of helpers into ember-cli-internal-test-helpers
https://github.com/ember-cli/ember-cli-blueprint-test-helpers/commit/899ec6a6c68ee4b9c27b6c9061ea682c535cf66a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
also I was having difficult running the tests with the instructions on the README of ``` node tests/nodetest-runner.js ```
> remove unneccessary lodash dependency

- README.md
- blueprints/blueprint-test/files/__root__/__name__-test.js
`ember-cli` blueprints should use `\n` for line breaks everywhere (see https://github.com/ember-cli/ember-cli/pull/5477) and importing `EOL` indirectly suggests to use native line breaks instead.
> blueprints/blueprint-test: Remove EOL import

- README.md
- lib/helpers/project-setup.js
This PR implements the idea expressed in https://github.com/ember-cli/ember-cli-blueprint-test-helpers/pull/28#issuecomment-188356411 and resolves https://github.com/ember-cli/ember-cli-blueprint-test-helpers/issues/27.
Essentially this feature is needed to be able to test mocha blueprints in e.g. `ember-data`
/cc @trabus @rwjblue
> Add "packages" option

- blueprints/ember-cli-blueprint-test-helpers/files/node-tests/nodetest-runner.js
- blueprints/ember-cli-blueprint-test-helpers/index.js
- package.json
As per [this conversation](https://github.com/emberjs/ember.js/pull/13029#discussion_r55144069) added RSVP as a dependency of nodetest-runner, so consuming projects don't have to depend on ember-cli.
> Added rsvp as dep for nodetest-runner to replace ember-cli/lib/ext/promise

- blueprints/ember-cli-blueprint-test-helpers/files/node-tests/nodetest-runner.js
As discussed in `ember-cli` `\n` should be used everywhere instead of native line breaks
> Remove EOLNEWLINE condition

- package.json
`glob` is required to develop this addon and run the tests, but it was missing from `package.json`. This PR adds it.
> Add glob to package.json

- README.md
- lib/helpers/blueprint-helper.js
The previous method for asserting thrown errors was flawed, instead switching to use chai-as-promised's `rejectedWith` method.
Also adapted throws option to accept strings, so all of the following are acceptable.
Example String:
```js
throws: 'Expected error message text.'
```
Example RegExp:
```js
throws: /Expected error message text./
```
Example object:
```js
throws: {
message: 'Expected message', 
type: 'SilentError'
}
// or
throws: {
message: /Expected message/,
type: 'SilentError'
}
```
> Fixes #34 fix assertThrows by using chai-as-promised rejectedWith

- blueprints/ember-cli-blueprint-test-helpers/files/node-tests/nodetest-runner.js
This should hopefully fix `Error: Cannot find module 'RSVP'` in https://travis-ci.org/emberjs/data/builds/119016376 (see https://github.com/emberjs/data/pull/4023)
> Fix require() call

- blueprints/blueprint-test/files/__root__/__name__-test.js
Fixing this so other people don't have to [scratch their heads like I did](https://github.com/kimroen/ember-cli-coffeescript/pull/106#issuecomment-200522734) :see_no_evil: (Thanks for helping out, @trabus!)
> Rename `contents` to `contains` in example assertion

- lib/helpers/blueprint-helper.js
Missing this resulted in "TypeError: expect(...).to.be.rejectedWith is not a function" (see https://github.com/emberjs/data/pull/4023)
/cc @trabus
> blueprint-helper: Explicitly use "chai-as-promised"

- package.json
This PR updates a few dependencies and moves two from `dependencies` to `devDependencies` that are only needed by our test runner.
> Dependency clean and updates

- README.md
- blueprints/blueprint-test/files/__root__/__name__-test.js
- chai.js
- helpers.js
- lib/ember-destroy.js
- lib/ember-generate-destroy.js
- lib/ember-generate.js
- lib/ember-new.js
- lib/helpers/setup.js
- lib/modify-packages.js
- lib/rethrow-from-error-log.js
- lib/setup-pod-config.js
- package.json
I'd like to propose a substantial API change for these helpers that should resolve #38, simplify the whole process of writing assertions and also greatly simplify our own code in this project.
Some examples:
```js
it('route foo', function() {
var args = ['route', 'foo'];
return emberNew()
.then(() => emberGenerate(args))
.then(() => expect(file('app/routes/foo.js'))
.to.contain('import Ember from \'ember\';')
.to.contain('export default Ember.Route.extend({\n});'))
.then(() => expect(file('app/templates/foo.hbs'))
.to.contain('{{outlet}}'))
.then(() => expect(file('tests/unit/routes/foo-test.js'))
.to.contain('import { moduleFor, test } from \'ember-qunit\';')
.to.contain('moduleFor(\'route:foo\''))
.then(() => expect(file('app/router.js'))
.to.contain('this.route(\'foo\')'))
.then(() => …
```
> A new Promise-based testing API

- README.md
- blueprints/blueprint-test/files/__root__/__name__-test.js
- blueprints/ember-cli-blueprint-test-helpers/index.js
- node-tests/blueprints/blueprint-test-test.js
- node-tests/blueprints/ember-cli-blueprint-test-helpers-test.js
- package.json
This PR adds the option to install babel dependencies for projects that need to test in node versions that don't support arrow functions natively. The user can run the default blueprint manually with the `-babel` option to install `babel-register`, `babel-plugin-transform-es2015-arrow-functions`, and `babel-plugin-transform-es2015-shorthand-properties`, with an accompanying `.babelrc`. Also, a `mocha.opts` file is added with `--require babel-register`.
Also added blueprint tests for `blueprint-test` and the default blueprint for `ember-cli-blueprint-test-helpers`. 
Still a WIP, I want to add documentation and clean up a few other things.
> Add babel option for default blueprint

- package.json
It seems like `rsvp` is actually a dependency of ember-cli-blueprint-test-helpers. Was finding it missing when trying to run tests for ember-cli-template-lint.
This PR moves `rsvp` to be a dependency and not a dev dependency for npm.
```
> ember-cli-template-lint@0.4.9 test-node /Users/ben/src/ember-cli-template-lint
> node node-tests/nodetest-runner.js
Error: Cannot find module 'rsvp'
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:278:25)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object.<anonymous> (/Users/ben/src/ember-cli-template-lint/node_modules/ember-cli-blueprint-test-helpers/lib/helpers/setup.js:3:24)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load …
```
> Move rsvp out of dev dependencies

- README.md
- blueprints/ember-cli-blueprint-test-helpers/index.js
- lib/ember-destroy.js
- lib/ember-generate.js
- lib/ember-new.js
- lib/helpers/ember.js
- lib/helpers/require-from-cli.js
- lib/helpers/setup.js
This PR makes the Ember CLI imports configurable. This enables us to use this project in Ember CLI itself where `require('ember-cli/something')` doesn't work.
Example:
```js
setupTestHooks(this, {
cliPath: path.resolve(__dirname + '/../../..'),
});
```
I'd like to release this as v0.13.0 rather soon so that we can begin using it in Ember CLI. This is currently blocking https://github.com/ember-cli/ember-cli/issues/5971.
@stefanpenner @trabus r?
> Decouple from Ember CLI

- README.md
- blueprints/ember-cli-blueprint-test-helpers/index.js
- node-tests/blueprints/ember-cli-blueprint-test-helpers-test.js
This was only necessary for Node 0.x, but those days are finally over... 🎉
> Remove obsolete --babel option

- README.md
- lib/helpers/setup.js
- node-tests/blueprints/ember-cli-blueprint-test-helpers-test.js
The result of the work of https://github.com/ember-cli/ember-cli-internal-test-helpers/issues/22.
This requires a little scrutiny because it will potentially break people that were depending on a real bower install already. We might need to muddy up the API with an opt-in mocking for bower...
cc @sivakumar-kailasam @Turbo87 @trabus
> mock bower install as well as npm

- lib/setup-pod-config.js
The current implementation does not work when using `let` (or `const` for that matters) instead of `var`.
> Make setupPodConfig helper agnostic of variable declaration type

- chai.js
- lib/helpers/setup.js
- tests/acceptance/helpers-test.js
This PR removes the symlink in `node_modules` left over by `emberNew`.
While this orphaned symlink is probably no big deal for most users other than being a bit awkward, it did have some serious side effects for me. It blew up a following `npm install` with the symlink in place causing some weird recursive installs, probably related to node-sass/node-gyp compilation. See these [logs](https://travis-ci.org/kaliber5/ember-bootstrap/jobs/210707736). And because Travis caches `node_modules`, this skrewed up all test runs (at least after the first uncached run).
> Cleanup symlinked addon after tests

- lib/ember-new.js
Support scoped packages by creating the scope directory under `node_modules`.
resolves #119
> Support scoped packages

- blueprints/ember-cli-blueprint-test-helpers/index.js
Copied from https://github.com/kellyselden/ember-datetimepicker/pull/152. Seems like a good idea since package.json is there in node_modules when installed.
> use mocha from package.json to keep versions permanently in sync

- lib/ember-new.js
- package.json
not needed in node 4+ land. no yarn changes.
> remove exists-sync

- README.md
- blueprints/blueprint-test/files/__root__/__name__-test.js
- blueprints/blueprint-test/index.js
- lib/ember-destroy.js
- lib/ember-generate-destroy.js
- lib/ember-generate.js
- lib/ember-new.js
- lib/helpers/cleanup-env.js
- package.json
- tests/acceptance/helpers-test.js
- yarn.lock
This PR unlocks the ability to do:
`emberNew({ isModuleUnification: true })`
or
`emberGenerateDestroy({ isModuleUnification: true })`
It would be especially usefull for testing blueprints in `ember.js` and `ember-data` repos + addons.
> Add MU support to blueprints test helpers

- .npmignore
to get rid of unnecessary weight (primarily `yarn.lock`)
> Adjust `.npmignore` file

- README.md
- blueprints/blueprint-test/files/__root__/__name__-test.js
This is a small PR just to update the test boilerplate to node >=6 syntax with the destructuring requires.  Also, I wanted to update the documentation since I was a bit lost since the examples did not have the "require" modules that included chai's "file" method that was needed when using "emberGenerate" and "emberDestroy".
> Fix Docs and modernize test

- package.json
- yarn.lock
This will hopefully fix AppVeyor CI... 😩
> Use tilde constraint for `ember-cli` dependency

- README.md
- blueprints/blueprint-test/files/__root__/__name__-test.js
- blueprints/blueprint-test/index.js
- lib/ember-destroy.js
- lib/ember-generate.js
- lib/ember-new.js
- tests/acceptance/helpers-test.js
Since Ember CLI no longer supports it either...
This will unblock any further PRs since our CI here does not use yarn and so it also does not use a lockfile for Ember CLI 😱
> Remove "Module Unification" support
